---
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:2025.1.3-enterprise
    stop_grace_period: 3600s
    network_mode: host
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs

  sonarqube-vmagent:
    container_name: sonarqube-vmagent
    depends_on:
      - sonarqube
    image: victoriametrics/vmagent:v1.93.15
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata

volumes:
  vmagentdata:
