---
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:2025.1.3-enterprise
    stop_grace_period: 3600s
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs
  
  sonarqube-ngrok:
    container_name: sonarqube-ngrok
    depends_on:
      - sonarqube
    image: ngrok/ngrok:3
    command:
      - "start"
      - "sonarqube"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

  sonarqube-vmagent:
    container_name: sonarqube-vmagent
    depends_on:
      - sonarqube
    image: victoriametrics/vmagent:v1.93.15
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata

volumes:
  vmagentdata:
