---
services:
  sonarqube:
    container_name: sonarqube
    depends_on:
      - sonarqube-postgres
    image: sonarqube:9.9.6-enterprise
    stop_grace_period: 3600s
    ports:
      - 9000:9000
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-postgres/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=123456
    volumes:
      - opt-sonarqube-data:/opt/sonarqube/data
      - opt-sonarqube-extensions:/opt/sonarqube/extensions
      - opt-sonarqube-logs:/opt/sonarqube/logs

  sonarqube-postgres:
    container_name: sonarqube-postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123456
    volumes:
      - var-lib-postgresql:/var/lib/postgresql
      - var-lib-postgresql-data:/var/lib/postgresql/data

  sonarqube-vmagent:
    container_name: sonarqube-vmagent
    depends_on:
      - sonarqube
    image: victoriametrics/vmagent:v1.93.15
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"

volumes:
  opt-sonarqube-data:
  opt-sonarqube-extensions:
  opt-sonarqube-logs:
  var-lib-postgresql:
  var-lib-postgresql-data:
  vmagentdata:
