---
services:
  sonarqube:
    container_name: sonarqube
    depends_on:
      - sonarqube-postgres
    image: sonarqube:2025.1.0-enterprise
    stop_grace_period: 3600s
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-postgres/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=123456
    volumes:
      - ./cacerts:/opt/java/openjdk/lib/security/cacerts
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs

  sonarqube-postgres:
    container_name: sonarqube-postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123456
    volumes:
      - var-lib-postgresql:/var/lib/postgresql
      - var-lib-postgresql-data:/var/lib/postgresql/data

  sonarqube-vmagent:
    container_name: sonarqube-vmagent
    depends_on:
      - sonarqube
    image: victoriametrics/vmagent:v1.93.15
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata

volumes:
  var-lib-postgresql:
  var-lib-postgresql-data:
  vmagentdata:
