---
version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 9002:5432/tcp
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - var-lib-postgresql:/var/lib/postgresql
      - var-lib-postgresql-data:/var/lib/postgresql/data

  sonarqube:
    container_name: sonarqube
    depends_on:
      - postgres
    image: sonarqube:9.9.5-enterprise
    stop_grace_period: 3600s
    ports:
      - 9000:9000/tcp
      - 9001:9001/tcp
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - opt-sonarqube-data:/opt/sonarqube/data
      - opt-sonarqube-extensions:/opt/sonarqube/extensions
      - opt-sonarqube-logs:/opt/sonarqube/logs

volumes:
  opt-sonarqube-data:
  opt-sonarqube-extensions:
  opt-sonarqube-logs:
  var-lib-postgresql:
  var-lib-postgresql-data:
