---
services:
  sonarqube-latest:
    container_name: sonarqube-latest
    depends_on:
      - sonarqube-latest-postgres
    image: sonarqube:2025.2.0-enterprise
    stop_grace_period: 3600s
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-latest-postgres/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=123456
      - SONAR_WEB_ACCESSLOGS_PATTERN=%h %l %reqAttribute{LOGIN} [%t] '%r' %s %b '%i{Referer}' '%i{User-Agent}' '%reqAttribute{ID}'
    networks:
      - sonarqube-latest-backend
    volumes:
      - ./cacerts:/opt/java/openjdk/lib/security/cacerts
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs

  sonarqube-latest-nginx:
    container_name: sonarqube-latest-nginx
    depends_on:
      - sonarqube-latest
    image: nginx:1.27
    networks:
      - sonarqube-latest-backend
      - sonarqube-latest-frontend
    ports:
      - 9010:80
      - 9011:443
      - 9012:81
    volumes:
      - ./server.crt:/etc/nginx/ssl/certificate.crt
      - ./server.key:/etc/nginx/ssl/private.key
      - ./nginx.conf:/etc/nginx/nginx.conf

  sonarqube-latest-postgres:
    container_name: sonarqube-latest-postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123456
    networks:
      - sonarqube-latest-backend
    volumes:
      - var-lib-postgresql:/var/lib/postgresql
      - var-lib-postgresql-data:/var/lib/postgresql/data
  
  sonarqube-latest-vmagent:
    container_name: sonarqube-latest-vmagent
    depends_on:
      - sonarqube-latest
    image: victoriametrics/vmagent:v1.93.15
    networks:
      - sonarqube-latest-backend
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata

networks:
  sonarqube-latest-backend:
  sonarqube-latest-frontend:

volumes:
  var-lib-postgresql:
  var-lib-postgresql-data:
  vmagentdata:
