---
services:
  sonarqube-latest:
    container_name: sonarqube-latest
    image: sonarqube:2025.4.2-enterprise
    stop_grace_period: 3600s
    networks:
      - sonarqube-latest-backend
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs

  sonarqube-latest-nginx:
    container_name: sonarqube-latest-nginx
    depends_on:
      - sonarqube-latest
    image: nginx:1.27
    networks:
      - sonarqube-latest-backend
      - sonarqube-latest-frontend
    ports:
      - 9010:80
      - 9011:443
    volumes:
      - ./server.crt:/etc/nginx/ssl/certificate.crt
      - ./server.key:/etc/nginx/ssl/private.key
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  sonarqube-latest-ngrok:
    container_name: sonarqube-latest-ngrok
    depends_on:
      - sonarqube-latest
    image: ngrok/ngrok:3
    command:
      - "start"
      - "sonarqube"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

  sonarqube-latest-vmagent:
    container_name: sonarqube-latest-vmagent
    depends_on:
      - sonarqube-latest
    image: victoriametrics/vmagent:v1.93.15
    networks:
      - sonarqube-latest-backend
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://host.docker.internal:8428/api/v1/write"
    volumes:
      - ./vmagent.yaml:/etc/prometheus/prometheus.yml
      - vmagentdata:/vmagentdata

networks:
  sonarqube-latest-backend:
  sonarqube-latest-frontend:

volumes:
  vmagentdata:
