---
version: "3.8"
services:
  postgres-latest:
    container_name: postgres-latest
    image: postgres:16
    ports:
      - 9012:5432/tcp
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - var-lib-postgresql:/var/lib/postgresql
      - var-lib-postgresql-data:/var/lib/postgresql/data

  sonarqube-latest:
    container_name: sonarqube-latest
    depends_on:
      - postgres-latest
    image: sonarqube:10.5.1-enterprise
    stop_grace_period: 3600s
    ports:
      - 9010:9000/tcp
      - 9011:9001/tcp
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-latest:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - ./conf:/opt/sonarqube/conf
      - opt-sonarqube-data:/opt/sonarqube/data
      - opt-sonarqube-extensions:/opt/sonarqube/extensions
      - opt-sonarqube-logs:/opt/sonarqube/logs

volumes:
  opt-sonarqube-data:
  opt-sonarqube-extensions:
  opt-sonarqube-logs:
  var-lib-postgresql:
  var-lib-postgresql-data:
