---
version: "3.8"
services:
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521
      - 5500
    network_mode: host
    environment:
      ORACLES_CHARACTERSET: AL32UTF8
      ORACLES_PWD: sonar
    volumes:
      - app_data:/opt/oracle/oradata

volumes:
  app_data:
