---
services:
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - 6389:389
      - 6636:636
    environment:
      # cn=admin,dc=waynekhan,dc=net
      - LDAP_DOMAIN=waynekhan.net
      - LDAP_ADMIN_PASSWORD=openldap

  phpldapadmin:
    depends_on:
      - openldap
    container_name: phpldapadmin
    image: osixia/phpldapadmin:latest
    ports:
      # https://localhost:6443
      - 6443:443/tcp
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
