---
services:
  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0  # cn=admin,dc=example,dc=org
    network_mode: host

  phpldapadmin:
    depends_on:
      - openldap
    container_name: phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 7443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=host.docker.internal
